name: 'Android Verifier Deployment'
on:
  push:
    tags:
      - android-v*

# Environment variables that are common to
# more than one deployment
env:
  STORE_FILE: "${{ github.workspace }}/android/verifier-keystore"
  GAPI_FILE_PATH: "${{ github.workspace }}/android/google-api.json"
  NDK_VERSION: "21.4.7075529" #make sure this will map to ndkVersifon in buildGradle
jobs:
  publishAndroidDev:
    timeout-minutes: 60
    if: contains(github.ref, 'release-dev')
    name: 'Build and Publish VerifierDev Bundle'
    runs-on: ubuntu-latest
    env:  
      STORE_PASSWORD: "${{secrets.DEV_STORE_PASSWORD}}"
      KEY_PASSWORD: "${{secrets.DEV_KEY_PASSWORD}}"
      KEY_ALIAS: "${{secrets.DEV_KEY_ALIAS}}"
    steps:
      - name: 'Checkout to branch'
        uses: actions/checkout@v2
      - name: 'Get release tag'
        id: release
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/})"
      - name: 'Create env file'
        run: |
          echo "${{ secrets.DEV_BUILD_CONFIG }}" >> .env.staging
      - name: 'Create google api file'
        run: |
          echo "${{ secrets.DEV_GCP_CREDS }}" > ${GAPI_FILE_PATH}.asc
          gpg --decrypt --passphrase "${{ secrets.DEV_GPG_PASSPHRASE }}" --batch ${GAPI_FILE_PATH}.asc > ${GAPI_FILE_PATH}
      - name: Install npm dependencies
        run: |
          npm install
      #    npx  react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.an
      # - name: Install google play dependencies
      #   run: |
      #     npx tsc tools/deploy/android/publisher.ts 2>/dev/null
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: 'Decrypt keystore and GCP credentials'
        working-directory: ./android
        run: |
          echo "${{ secrets.DEV_KEYSTORE }}" > verifier-keystore.asc
          gpg --decrypt --passphrase "${{ secrets.DEV_GPG_PASSPHRASE }}" --batch verifier-keystore.asc > verifier-keystore
          touch local.properties

      - name: 'Build devRelease'
        working-directory: ./android
        run: ./gradlew :app:bundleDevRelease  --no-daemon --info

      - name: 'Publish to the store'
        run: >
          node tools/deploy/android/androidDeploy.js 
          --googleApiKeyFilePath ${GAPI_FILE_PATH}
          --aabFilePath ./android/app/build/outputs/bundle/devRelease/app-dev-release.aab 
          --env dev  
          --status draft

  publishAndroidProd:
    timeout-minutes: 60
    if: contains(github.ref, 'release-prod')
    name: 'Build and Publish Verifier Bundle'
    runs-on: ubuntu-latest
    env:  
      STORE_PASSWORD: "${{secrets.PROD_STORE_PASSWORD}}"
      KEY_PASSWORD: "${{secrets.PROD_KEY_PASSWORD}}"
      KEY_ALIAS: "${{secrets.PROD_KEY_ALIAS}}"
    steps:
      - name: 'Checkout to branch'
        uses: actions/checkout@v2
      - name: 'Get release tag'
        id: release
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF##*/})"
      - name: 'Create env file'
        run: |
          echo "${{ secrets.PROD_BUILD_CONFIG }}" >> .env.production
      - name: 'Create google api file'
        run: |
          echo "${{ secrets.PROD_GCP_CREDS }}" > ${GAPI_FILE_PATH}.asc
          gpg --decrypt --passphrase "${{ secrets.PROD_GPG_PASSPHRASE }}" --batch ${GAPI_FILE_PATH}.asc > ${GAPI_FILE_PATH}
      - name: Install npm dependencies
        run: |
          npm install
      # - name: Install google play dependencies
      #   run: |
      #     npx tsc tools/deploy/android/publisher.ts 2>/dev/null
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}"
      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: 'Decrypt keystore and GCP credentials'
        working-directory: ./android
        run: |
          echo "${{ secrets.PROD_KEYSTORE }}" > verifier-keystore.asc
          gpg --decrypt --passphrase "${{ secrets.PROD_GPG_PASSPHRASE }}" --batch verifier-keystore.asc > verifier-keystore
          touch local.properties

      - name: 'Build prodRelease'
        working-directory: ./android
        run: ./gradlew :app:bundleProdRelease  --no-daemon --info
      - name: 'Install Tool'
        run: |
          npm install publish-aab-google-play
      - name: 'Publish to the store'
        run: >
          node tools/deploy/android/androidDeploy.js 
          --googleApiKeyFilePath ${GAPI_FILE_PATH}
          --aabFilePath ./android/app/build/outputs/bundle/prodRelease/app-prod-release.aab 
          --env prod
          --status draft

