name: learn-github-actions
on:
  push:
    types: [opened, synchronize]
jobs:
  check-code-readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
